name = "mcp-poc"
version = "0.1.0"
component = "/Users/colinrozzi/work/actors/mcp-poc/./target/wasm32-unknown-unknown/release/mcp_poc.wasm"
description = "MCP Server Integration Proof of Concept"
init_state = "/Users/colinrozzi/work/actors/mcp-poc/init.json"

[[handlers]]
type = "message-server"

[handlers.config]

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "process"

[handlers.config]
max_processes = 10
max_output_buffer = 1048576

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1
