package colinrozzi:mcp-poc;

world default {
    import theater:simple/runtime;
    import theater:simple/process;
    import theater:simple/message-server-host;
    import theater:simple/timing;

    export theater:simple/message-server-client;
    export theater:simple/actor;
    export theater:simple/process-handlers;
}
